from core.protocol_state import ProtocolSpec, VerificationResult
from core.runtime_config import load_runtime_config
from verifiers.murphi_tool import MurphiTool

class MurphiRunner:
    """
    Murphi Runner:
    Takes the formal specification generated by the Agent, compiles it,
    runs the bounded model checking, and checks core properties.
    """
    def __init__(self, murphi_path: str | None = None):
        default_path = load_runtime_config()["murphi"]["compiler"]
        self.murphi_path = murphi_path or default_path
        self.tool = MurphiTool(murphi_compiler=self.murphi_path)

    def run_verification(self, spec: ProtocolSpec) -> VerificationResult:
        """
        Executes the model checking using the standalone MurphiTool.
        Returns success or a counterexample trace.
        """
        print(f"[MurphiRunner] Compiling and running Murphi model checking for '{spec.name}'...")

        result = self.tool.run_check(spec.murphi_code)
        
        if result["status"] == "success":
            return VerificationResult(is_success=True)
        if result["status"] == "failed":
            # Extract structured trace and format it as string for the older agent code
            trace_str = f"Trace Length: {result.get('trace_length')}\n"
            for step in result.get('counterexample_trace', []):
                trace_str += f"Step {step['step']}: {step['action']} -> {step['state_changes']}\n"
                
            return VerificationResult(
                is_success=False,
                counterexample_trace=trace_str,
                failed_invariant=result.get("violated_invariant", "Unknown")
            )
        return VerificationResult(
            is_success=False,
            counterexample_trace=result.get("details") or result.get("message") or str(result),
            failed_invariant=result.get("error_type", "ExecutionError"),
        )
