from core.protocol_state import ProtocolSpec, VerificationResult

class MurphiRunner:
    """
    Murphi Runner:
    Takes the formal specification generated by the Agent, compiles it,
    runs the bounded model checking, and checks core properties.
    """
    def __init__(self, murphi_path: str = "mu"):
        self.murphi_path = murphi_path

    def run_verification(self, spec: ProtocolSpec) -> VerificationResult:
        """
        Executes the model checking. Returns success or a counterexample trace.
        """
        print(f"[MurphiRunner] Compiling and running Murphi model checking for '{spec.name}'...")
        
        # Here we would write `spec.murphi_code` to a `.m` file, compile with C++, and run the binary.
        # Example flow:
        # 1. Write `spec.murphi_code` to `model.m`
        # 2. Subprocess: `mu model.m` -> `model.cpp`
        # 3. Subprocess: `g++ -O3 model.cpp -o model`
        # 4. Subprocess: `./model`
        # 5. Parse output to check for violation.
        
        # Mocked return for framework structure:
        # We will simulate a failure on the first run, and success on subsequent runs to show iteration.
        if not hasattr(self, 'run_count'):
            self.run_count = 0
        self.run_count += 1
        
        if self.run_count == 1:
            is_success = False  # Let's pretend it found a bug first time
        else:
            is_success = True   # Pretend the refiner fixed it!
            
        trace = "Trace: state S -> event BusRdX -> bug: multiple M states."
        
        if is_success:
            return VerificationResult(is_success=True)
        else:
            return VerificationResult(
                is_success=False,
                counterexample_trace=trace,
                failed_invariant="Invariant 'Only one node can be in M state' violated."
            )
