from core.protocol_state import ProtocolSpec, VerificationResult
from verifiers.murphi_tool import MurphiTool

class MurphiRunner:
    """
    Murphi Runner:
    Takes the formal specification generated by the Agent, compiles it,
    runs the bounded model checking, and checks core properties.
    """
    def __init__(self, murphi_path: str = "mu"):
        self.murphi_path = murphi_path
        self.tool = MurphiTool(murphi_compiler=murphi_path)

    def run_verification(self, spec: ProtocolSpec) -> VerificationResult:
        """
        Executes the model checking using the standalone MurphiTool.
        Returns success or a counterexample trace.
        """
        print(f"[MurphiRunner] Compiling and running Murphi model checking for '{spec.name}'...")
        
        # Call the standalone MCP Tool
        # We mock a BUG condition to simulate iteration for the framework if it's the first run
        if not hasattr(self, 'run_count'):
            self.run_count = 0
        self.run_count += 1
        
        code_to_run = spec.murphi_code
        if self.run_count == 1 and "BUG" not in code_to_run:
            # Force a mock bug for the pilot framework demonstration
            code_to_run += "\nBUG"
            
        result = self.tool.run_check(code_to_run)
        
        if result["status"] == "success":
            return VerificationResult(is_success=True)
        else:
            # Extract structured trace and format it as string for the older agent code
            trace_str = f"Trace Length: {result.get('trace_length')}\n"
            for step in result.get('counterexample_trace', []):
                trace_str += f"Step {step['step']}: {step['action']} -> {step['state_changes']}\n"
                
            return VerificationResult(
                is_success=False,
                counterexample_trace=trace_str,
                failed_invariant=result.get("violated_invariant", "Unknown")
            )
